"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import { SnackbarProvider } from "notistack";
import { SnackbarUtilsConfigurator } from "@/components/customs/CustomNotification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SnackbarProvider
          maxSnack={2}
          anchorOrigin={{ vertical: "top", horizontal: "right" }}
        >
          <SnackbarUtilsConfigurator />
          <ReduxProvider>{children}</ReduxProvider>
        </SnackbarProvider>
      </body>
    </html>
  );
}
